#:schema node_modules/wrangler/config-schema.json
name = "er-score"
pages_build_output_dir = ".svelte-kit/cloudflare/"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "er-score"
database_id = "e79d5a39-8364-479d-9e7a-93c6168c7a70"
migrations_dir = "drizzle/migrations"
