// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ko'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	searchForm: {
		/**
		 * 유​저​ ​이​름
		 */
		label: string
		/**
		 * 유​저​ ​이​름​을​ ​입​력​해​주​세​요​.
		 */
		placeholder: string
		/**
		 * 검​색
		 */
		search: string
	}
	recentMatches: {
		/**
		 * 정​보​가​ ​없​습​니​다​.
		 */
		noData: string
	}
	userRecords: {
		heading: {
			/**
			 * 순​위
			 */
			rank: string
			/**
			 * 승​패
			 */
			winLose: string
			/**
			 * 이​름
			 */
			name: string
			/**
			 * 점​수
			 */
			score: string
			/**
			 * K
			 */
			k: string
			/**
			 * D
			 */
			d: string
			/**
			 * A
			 */
			a: string
			/**
			 * 장​비
			 */
			equipments: string
			/**
			 * 딜
			 */
			damageDealtToPlayers: string
			/**
			 * 탱
			 */
			damageTakenFromPlayers: string
			/**
			 * 힐
			 */
			healingAmount: string
		}
		value: {
			/**
			 * 승
			 */
			win: string
			/**
			 * 패
			 */
			lose: string
			/**
			 * {​r​a​n​k​}​위
			 * @param {number} rank
			 */
			rank: RequiredParams<'rank'>
		}
		/**
		 * 사​전​구​성​ ​{​n​}​인​ ​팀
		 * @param {number} n
		 */
		preMadeTeamSize: RequiredParams<'n'>
		/**
		 * 정​보​ ​없​음
		 */
		noData: string
	}
	matchingMode: {
		/**
		 * 일​반
		 */
		'2': string
		/**
		 * 랭​크
		 */
		'3': string
		/**
		 * 코​발​트
		 */
		'6': string
		/**
		 * 유​니​온
		 */
		'8': string
		/**
		 * 전​체
		 */
		all: string
	}
	stats: {
		heading: {
			/**
			 * 횟​수
			 */
			count: string
			/**
			 * 점​수
			 */
			score: string
			/**
			 * 반​타​작​률
			 */
			halfRate: string
			/**
			 * 평​균​ ​딜
			 */
			averageDamage: string
		}
		/**
		 * 최​근​ ​{​n​}​일​간
		 * @param {number} n
		 */
		recentNDays: RequiredParams<'n'>
		/**
		 * (​최​대​ ​{​l​i​m​i​t​}​경​기​)
		 * @param {number} limit
		 */
		limitHint: RequiredParams<'limit'>
	}
	button: {
		/**
		 * 열​기
		 */
		open: string
		/**
		 * 닫​기
		 */
		close: string
		/**
		 * 자​세​히
		 */
		detail: string
	}
	refresh: {
		/**
		 * 전​적​ ​갱​신
		 */
		text: string
		/**
		 * [​F​5​]
		 */
		keyboard: string
	}
	status: {
		/**
		 * 페​이​지​를​ ​찾​을​ ​수​ ​없​습​니​다​.
		 */
		'404': string
	}
}

export type TranslationFunctions = {
	searchForm: {
		/**
		 * 유저 이름
		 */
		label: () => LocalizedString
		/**
		 * 유저 이름을 입력해주세요.
		 */
		placeholder: () => LocalizedString
		/**
		 * 검색
		 */
		search: () => LocalizedString
	}
	recentMatches: {
		/**
		 * 정보가 없습니다.
		 */
		noData: () => LocalizedString
	}
	userRecords: {
		heading: {
			/**
			 * 순위
			 */
			rank: () => LocalizedString
			/**
			 * 승패
			 */
			winLose: () => LocalizedString
			/**
			 * 이름
			 */
			name: () => LocalizedString
			/**
			 * 점수
			 */
			score: () => LocalizedString
			/**
			 * K
			 */
			k: () => LocalizedString
			/**
			 * D
			 */
			d: () => LocalizedString
			/**
			 * A
			 */
			a: () => LocalizedString
			/**
			 * 장비
			 */
			equipments: () => LocalizedString
			/**
			 * 딜
			 */
			damageDealtToPlayers: () => LocalizedString
			/**
			 * 탱
			 */
			damageTakenFromPlayers: () => LocalizedString
			/**
			 * 힐
			 */
			healingAmount: () => LocalizedString
		}
		value: {
			/**
			 * 승
			 */
			win: () => LocalizedString
			/**
			 * 패
			 */
			lose: () => LocalizedString
			/**
			 * {rank}위
			 */
			rank: (arg: { rank: number }) => LocalizedString
		}
		/**
		 * 사전구성 {n}인 팀
		 */
		preMadeTeamSize: (arg: { n: number }) => LocalizedString
		/**
		 * 정보 없음
		 */
		noData: () => LocalizedString
	}
	matchingMode: {
		/**
		 * 일반
		 */
		'2': () => LocalizedString
		/**
		 * 랭크
		 */
		'3': () => LocalizedString
		/**
		 * 코발트
		 */
		'6': () => LocalizedString
		/**
		 * 유니온
		 */
		'8': () => LocalizedString
		/**
		 * 전체
		 */
		all: () => LocalizedString
	}
	stats: {
		heading: {
			/**
			 * 횟수
			 */
			count: () => LocalizedString
			/**
			 * 점수
			 */
			score: () => LocalizedString
			/**
			 * 반타작률
			 */
			halfRate: () => LocalizedString
			/**
			 * 평균 딜
			 */
			averageDamage: () => LocalizedString
		}
		/**
		 * 최근 {n}일간
		 */
		recentNDays: (arg: { n: number }) => LocalizedString
		/**
		 * (최대 {limit}경기)
		 */
		limitHint: (arg: { limit: number }) => LocalizedString
	}
	button: {
		/**
		 * 열기
		 */
		open: () => LocalizedString
		/**
		 * 닫기
		 */
		close: () => LocalizedString
		/**
		 * 자세히
		 */
		detail: () => LocalizedString
	}
	refresh: {
		/**
		 * 전적 갱신
		 */
		text: () => LocalizedString
		/**
		 * [F5]
		 */
		keyboard: () => LocalizedString
	}
	status: {
		/**
		 * 페이지를 찾을 수 없습니다.
		 */
		'404': () => LocalizedString
	}
}

export type Formatters = {}
